# Generated by Django 3.1.7 on 2021-03-23 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210323_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='/media/default.png', upload_to='media')),
                ('user_bio', models.CharField(blank=True, max_length=150)),
                ('user_external_link', models.URLField(blank=True, default='')),
                ('user_follower', models.IntegerField(default=0)),
                ('user_following', models.IntegerField(default=0)),
                ('user_total_post', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
