# Generated by Django 3.1.7 on 2021-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followed_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_post_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_like_count',
            field=models.IntegerField(default=0),
        ),
    ]
