# Generated by Django 3.1.7 on 2021-05-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210511_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='is_post_liked',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_like_count',
        ),
    ]
