# Generated by Django 3.1.7 on 2021-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210511_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostsaved',
            name='post',
            field=models.ManyToManyField(related_name='saved_post', to='core.UserPost'),
        ),
    ]
