# Generated by Django 3.1.7 on 2021-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210511_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostsaved',
            old_name='post',
            new_name='saved_post',
        ),
    ]
