# Generated by Django 3.1.7 on 2021-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210511_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_saved_post',
            field=models.ManyToManyField(related_name='saved_post', to='core.Like'),
        ),
        migrations.DeleteModel(
            name='UserPostSaved',
        ),
    ]
