# Generated by Django 3.1.1 on 2021-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210512_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='/media/default.png', upload_to='user_profile_images'),
        ),
    ]
